# Use root/example as user/password credentials
version: '3.1'

services:

  mongo:
    image: mongo
    container_name: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - ./data/dev/mongo:/data/db

  api:
    image: ${DOCKER_REGISTRY-}manga-bookmarker-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - 'mongo'